version: '3'

services:
  rental:
    build:
      context: .
      dockerfile: Dockerfile
    image: rental
    volumes:
    - .:/opt/app
    working_dir: /opt/app
    ports:
      - 8001:8001
    tty: true
    environment:
      - SECRET_KEY=super_secret
      - DB_HOST=db
      - DB_NAME=rental_db
      - DB_USER=rental_db_user
      - DB_PASS=rental_db_pass
      - DB_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db
    command: bash -c "sh ./entrypoint.sh &&
                      python demo/manage.py migrate && 
                      python demo/manage.py runserver 0.0.0.0:8001"

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=rental_db_user
      - POSTGRES_PASSWORD=rental_db_pass
      - POSTGRES_DB=rental_db
    ports:
      - "54320:5432"

volumes:
  postgres_data: